# Copyright (c) 2025 Valentin Boussot
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""The shipped ``examples/Transform`` configs, run as shipped.

An example is the first thing a new user runs, and the only one whose breakage they read as the
framework being broken. These are copied verbatim (not templated, not rewritten), so a rename in
the transform grammar fails here rather than in someone's terminal.

The cohort is generated by the example's own ``make_dataset.py``: six small volumes, no download,
a few seconds each way.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import pytest
from harness import konfai_cli_command, subprocess_env

EXAMPLE = Path(__file__).resolve().parents[2] / "examples" / "Transform"


def _run(command: list[str], workdir: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, capture_output=True, text=True, env=subprocess_env(), cwd=workdir, timeout=900)


@pytest.fixture(scope="module")
def cohort(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """The example directory, with the cohort its own script generates."""
    assert EXAMPLE.is_dir(), f"the example this guards is not where it is expected: {EXAMPLE}"
    workdir = tmp_path_factory.mktemp("transform_example")
    for name in ("Transform.yml", "Transform_expand.yml", "make_dataset.py"):
        shutil.copy(EXAMPLE / name, workdir / name)
    made = _run([sys.executable, "make_dataset.py"], workdir)
    assert made.returncode == 0, f"make_dataset.py failed:\n{made.stdout}{made.stderr}"
    assert sorted(p.name for p in (workdir / "Raw").iterdir()) == [f"CASE_{i:03d}" for i in range(6)]
    return workdir


@pytest.mark.integration
def test_the_template_example_folds_the_cohort_into_one_entry(cohort: Path) -> None:
    """N to 1. The README's headline claim, and the reason a reference Resample is in the chain:
    the cases do not share a grid, so ``grid: strict`` would refuse them as stored."""
    planned = _run([*konfai_cli_command(), "TRANSFORM", "--config", "Transform.yml", "--plan"], cohort)
    assert planned.returncode == 0, f"the template example does not plan:\n{planned.stdout}{planned.stderr}"
    assert "REDUCE 6 case(s) -> 1 output 'template'" in planned.stdout
    # --plan probes each destination with a real region-write open, so the store itself may be
    # created; what it must not leave behind is an entry, the probe's own included.
    assert not (cohort / "Template" / "template").exists(), "--plan must not write the deliverable"
    assert [p.name for p in (cohort / "Template").iterdir()] == [], "--plan must remove what it probed with"

    executed = _run([*konfai_cli_command(), "TRANSFORM", "--config", "Transform.yml"], cohort)
    assert executed.returncode == 0, f"the template example does not run:\n{executed.stdout}{executed.stderr}"
    assert (cohort / "Template" / "template" / "CT_template.mha").is_file()


@pytest.mark.integration
def test_the_expand_example_writes_one_entry_per_drawn_copy(cohort: Path) -> None:
    """1 to N, and the copies are named by the config's own pattern, which is what a second chain
    reading them back has to agree with."""
    executed = _run([*konfai_cli_command(), "TRANSFORM", "--config", "Transform_expand.yml"], cohort)
    assert executed.returncode == 0, f"the expand example does not run:\n{executed.stdout}{executed.stderr}"

    written = sorted(p.name for p in (cohort / "Augmented").iterdir())
    assert written == [f"CASE_{case:03d}_r{copy:02d}" for case in range(6) for copy in range(1, 5)]
