# Copyright (c) 2025 Valentin Boussot
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""Pull-knowledge primitives: what KonfAI can do, and the schema of a workflow config.

These are deliberately *thin* and *generated*, not prose duplicated from the docs:

* ``describe_konfai_capabilities`` is a hub that points the agent at the right tools/resources
  (and at AGENTS.md as the single source of truth) instead of re-encoding KonfAI's rules.
* ``describe_config_schema`` is generated by introspecting the Trainer/Predictor/Evaluator
  constructors via the reflection engine, so it never drifts from the actual config contract.

The intent is the right abstraction level: give the agent capabilities + a schema to reason
about, not a step-by-step workflow to execute.
"""

from __future__ import annotations

import importlib
import inspect
import types
from typing import Any, Union, get_args, get_origin

from konfai_mcp.workflows import WORKFLOW_SPECS

# Workflow -> (root YAML key, module, class name).
_WORKFLOW_ROOTS = {kind: (spec.root_key, spec.module, spec.class_name) for kind, spec in WORKFLOW_SPECS.items()}

_WORKFLOW_ALIASES = {alias: kind for kind, spec in WORKFLOW_SPECS.items() for alias in spec.aliases}


def describe_konfai_capabilities() -> dict[str, Any]:
    """A capability overview that routes the agent to the right primitives (not a workflow script)."""
    return {
        "summary": (
            "KonfAI is a declarative YAML deep-learning framework for medical imaging: every component "
            "(model, data pipeline, losses/metrics, optimizer/schedulers, augmentations, transforms, and the "
            "train/predict/evaluate workflow) is described in YAML and mapped to Python objects by a reflection "
            "engine. You compose a solution; KonfAI instantiates it. The config doubles as a reproducible record."
        ),
        "canonical_reference": "AGENTS.md (the single source of truth for KonfAI rules and conventions).",
        "workflows": {
            "train": "Config.yml (Trainer:) -> run_train",
            "prediction": "Prediction.yml (Predictor:) -> run_prediction",
            "evaluation": "Evaluation.yml (Evaluator:) -> run_evaluation",
            "schema_tool": "describe_config_schema(workflow)",
        },
        "components": {
            "kinds": ["criterion (loss/metric)", "transform", "augmentation", "scheduler", "model", "block"],
            "discover": "list_components(kind)",
            "inspect": "inspect_object_signature(classpath)",
        },
        "extension_model": {
            "principle": "Subclass a base, reference it by classpath in YAML -- no core edits.",
            "describe": "describe_extension_points(kind)",
            "external_libraries": "Reference an installed library class directly via `package.module:Class` "
            "(e.g. monai.losses:DiceLoss); vet it first with check_external_dependency.",
        },
        "apps": {
            "principle": "When the user wants a RESULT, check published apps FIRST -- cheapest fit wins: "
            "use an app as-is, else fine-tune one, else train from scratch.",
            "use_dont_train": "list_apps -> describe_app -> list_app_parameters -> import_app "
            "(copies the app into the session) -> run_prediction with the returned checkpoints",
            "fine_tune": "import_app -> run_resume(weights_only=True) (warm start from the app's weights on the "
            "user's dataset, fresh optimizer/epoch)",
            "resume": "run_resume (true RESUME of an interrupted session training: optimizer/epoch restored)",
            "package": "package_app_from_session / export_app (turn a trained session or tuned app into a bundle)",
        },
        "modeling_modes": "2D / 2.5D (extend_slice>0, patch_size[0]==1) / 3D, set via the Patch block.",
        "advanced": [
            "patch-based learning + overlap-blended reassembly",
            "test-time augmentation (TTA) and model ensembling (Predictor.outputs_dataset / combine)",
            "deep supervision / multi-head / intermediate-feature losses via named module outputs (outputs_criterions)",
            "multi-model setups (GAN, teacher-student) -- requires a Network subclass, not a black-box wrap",
        ],
        "safe_actions": [
            "inspect_dataset, list_components, describe_*, inspect_object_signature",
            "write_workflow_config / write_session_file (authoring)",
            "validate_config_semantics (side-effect-free), check_external_dependency (no import side effects)",
            "run_component_smoke_test (executes a custom transform/criterion contract in an isolated subprocess)",
            "read_live_metrics, leaderboard, summarize_session (read-only)",
        ],
        "risky_actions_prefer_human_confirmation": [
            "run_train / run_prediction / run_evaluation (commits GPU/compute)",
            "executing agent-authored or downloaded Python (validation imports workspace code)",
            "adding an external dependency or accepting its license",
            "selecting the final model / preparing a submission",
            "destructive dataset operations (move/overwrite)",
        ],
        "next_actions": [
            "list_apps",
            "inspect_dataset",
            "describe_config_schema",
            "list_components",
            "describe_extension_points",
        ],
    }


def _is_scalar(value: Any) -> bool:
    return value is None or isinstance(value, (str, int, float, bool))


def _serialize(value: Any) -> Any:
    # Surface scalar defaults AND flat containers of scalars -- patch_size=[128,128,128], channel lists,
    # overlap windows, and scalar class maps are load-bearing tunables the agent must see. Nested @config
    # object defaults still carry volatile object reprs, so those return None (drill via nested_config_classpath).
    if _is_scalar(value):
        return value
    if isinstance(value, (list, tuple)) and all(_is_scalar(item) for item in value):
        return list(value)
    if isinstance(value, dict) and all(_is_scalar(key) and _is_scalar(item) for key, item in value.items()):
        return dict(value)
    return None


def _annotation_text(annotation: Any) -> str | None:
    if annotation is inspect.Parameter.empty:
        return None
    return getattr(annotation, "__name__", None) or str(annotation)


def _unwrap_annotation(annotation: Any) -> Any:
    """Return the underlying class of an Optional/Union annotation, else the annotation unchanged.

    KonfAI declares nested config fields as e.g. ``patch: DatasetPatch | None = DatasetPatch()``, so the
    raw annotation is a UnionType, not a class -- without unwrapping, every OPTIONAL nested @config
    (Patch, augmentations, EarlyStopping, ModelPatch, ...) would be reported as non-drillable even though
    the tool advertises drilling into them. Generic: works for both ``X | None`` and ``Optional[X]``.
    """
    if get_origin(annotation) in (Union, types.UnionType):
        non_none = [arg for arg in get_args(annotation) if arg is not type(None)]
        if len(non_none) == 1:
            return non_none[0]
    return annotation


def _nested_config_classpath(annotation: Any) -> str | None:
    # The reflection engine tags @config classes with a ``_key`` attribute; such a parameter is a
    # nested config object the agent can drill into with inspect_object_signature (unwrap Optional first).
    resolved = _unwrap_annotation(annotation)
    if inspect.isclass(resolved) and getattr(resolved, "_key", None) is not None:
        return f"{resolved.__module__}:{resolved.__qualname__}"
    return None


def normalize_workflow(workflow: str) -> str:
    canonical = _WORKFLOW_ALIASES.get(workflow.strip().lower(), workflow.strip().lower())
    if canonical not in _WORKFLOW_ROOTS:
        raise ValueError(f"Unknown workflow '{workflow}'. Expected one of: {', '.join(_WORKFLOW_ROOTS)}.")
    return canonical


def _field_payloads(cls: Any) -> list[dict[str, Any]]:
    parameters = list(inspect.signature(cls.__init__).parameters.values())[1:]
    fields = []
    for parameter in parameters:
        annotation = parameter.annotation
        resolved = _unwrap_annotation(annotation)
        nested_key = getattr(resolved, "_key", None) if inspect.isclass(resolved) else None
        has_default = parameter.default is not inspect.Parameter.empty
        serialized_default = _serialize(parameter.default)
        # A non-scalar, non-None default (a nested @config object) can't be serialized cleanly; say so
        # explicitly so `default:null, required:false` is not mistaken for "no default".
        default_hidden = has_default and serialized_default is None and parameter.default is not None
        fields.append(
            {
                "name": parameter.name,
                # The literal key to write in the YAML: nested @config objects use their _key
                # (e.g. Model, Dataset); plain parameters use the parameter name as-is.
                "yaml_key": nested_key or parameter.name,
                "type": _annotation_text(annotation),
                "default": serialized_default,
                "required": not has_default,
                "default_hidden": default_hidden,
                "nested_config_classpath": _nested_config_classpath(annotation),
            }
        )
    return fields


def describe_config_schema(workflow: str, path: str | None = None) -> dict[str, Any]:
    """Describe a workflow config schema level, generated from the constructors (drill with ``path``)."""
    import re as _re

    canonical = normalize_workflow(workflow)
    root_key, module_name, class_name = _WORKFLOW_ROOTS[canonical]
    cls = getattr(importlib.import_module(module_name), class_name)
    yaml_path = [root_key]
    if path:
        for token in [part for part in _re.split(r"[.:/]", path) if part]:
            parameters = list(inspect.signature(cls.__init__).parameters.values())[1:]
            match_cls = None
            for parameter in parameters:
                resolved = _unwrap_annotation(parameter.annotation)  # unwrap `X | None` -> X
                nested_key = getattr(resolved, "_key", None) if inspect.isclass(resolved) else None
                if token in {parameter.name, nested_key} or token.lower() == parameter.name.lower():
                    match_cls = resolved
                    break
            if match_cls is None or not inspect.isclass(match_cls) or getattr(match_cls, "_key", None) is None:
                drillable = [
                    getattr(_unwrap_annotation(p.annotation), "_key", None) or p.name
                    for p in parameters
                    if inspect.isclass(_unwrap_annotation(p.annotation))
                    and getattr(_unwrap_annotation(p.annotation), "_key", None) is not None
                ]
                raise ValueError(
                    f"Cannot drill into '{token}' under {'.'.join(yaml_path)}. "
                    f"Drillable nested config keys here: {drillable or 'none'}."
                )
            cls = match_cls
            yaml_path.append(getattr(cls, "_key", token))

    return {
        "workflow": canonical,
        "root_key": root_key,
        "yaml_path": yaml_path,
        "classpath": f"{cls.__module__}:{cls.__qualname__}",
        "fields": _field_payloads(cls),
        "reference_hint": (
            f"These are the keys under {':'.join(yaml_path)}:. Each field's yaml_key is the literal key to write. "
            "Scalar and flat-list/dict defaults are shown in 'default'; a field with default_hidden=true HAS a "
            "default that is just not JSON-serializable here (usually a nested config object) -- read it with "
            "inspect_object_signature on nested_config_classpath. Drill deeper with path='Dataset.Patch'-style "
            "tokens; see the example templates for full, working configs."
        ),
        "next_actions": [
            "describe_config_schema",
            "inspect_object_signature",
            "list_components",
            "write_workflow_config",
        ],
    }
