# Copyright (c) 2025 Valentin Boussot
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""Build image-only IMPACT-Reg controlled-offset evidence panels.

The input payload is a real MR volume. Its origin is deliberately shifted while
the voxel bytes remain unchanged, creating a reproducible registration stress
test. The reader requests one plane at a time; compressed sources may still be
decompressed internally by the imaging backend.
Composite desktop/mobile proof boards remain available through explicit output
arguments, but are not generated by default.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from generate_app_proof_gallery import (
    ACCENT,
    BACKGROUND,
    CARD,
    CARD_HEIGHT,
    CARD_WIDTH,
    INK,
    MUTED,
    body_crop,
    crop_array,
    fit,
    fonts,
    robust_gray,
    window_gray,
)
from PIL import Image, ImageDraw, ImageOps

CARDS_DIR = Path(__file__).parents[1] / "source" / "_static" / "apps" / "impact-reg"


@dataclass(frozen=True)
class RegistrationSummary:
    """Bounded-read validation summary for a registration run."""

    before_ncc: float
    after_ncc: float
    before_mae: float
    after_mae: float
    dvf_mean: float
    dvf_p95: float
    dvf_p99: float
    dvf_max: float
    dx: int
    dy: int


def image_reader(path: Path):
    """Open metadata without materialising the image."""
    import SimpleITK as sitk

    reader = sitk.ImageFileReader()
    reader.SetFileName(str(path))
    reader.ReadImageInformation()
    return reader


def require_matching_grid(actual, expected, label: str, *, compare_origin: bool = True) -> None:
    """Require matching image-grid metadata without reading voxel payloads."""
    if actual.GetSize() != expected.GetSize():
        raise ValueError(f"{label} size does not match the expected grid")
    for field, getter in (("spacing", "GetSpacing"), ("direction", "GetDirection")):
        if not np.allclose(getattr(actual, getter)(), getattr(expected, getter)()):
            raise ValueError(f"{label} {field} does not match the expected grid")
    if compare_origin and not np.allclose(actual.GetOrigin(), expected.GetOrigin()):
        raise ValueError(f"{label} origin does not match the expected grid")


def plane_coordinate(reader, axis: int, index: int) -> float:
    """Return a plane's signed physical coordinate along one image axis."""
    direction = np.asarray(reader.GetDirection(), dtype=np.float64).reshape(3, 3)
    indices = np.zeros(3, dtype=np.float64)
    indices[axis] = index
    point = np.asarray(reader.GetOrigin()) + direction @ (indices * np.asarray(reader.GetSpacing()))
    return float(np.dot(direction[:, axis], point))


def read_axial(reader, index: int) -> np.ndarray:
    """Read one Z plane from an existing SimpleITK reader."""
    import SimpleITK as sitk

    size_x, size_y, size_z = reader.GetSize()
    if not 0 <= index < size_z:
        raise ValueError(f"Axial index {index} outside [0, {size_z - 1}]")
    reader.SetExtractIndex([0, 0, index])
    reader.SetExtractSize([size_x, size_y, 1])
    return np.asarray(sitk.GetArrayFromImage(reader.Execute())).squeeze().astype(np.float64)


def read_coronal(reader, index: int) -> np.ndarray:
    """Read one Y plane from an existing SimpleITK reader."""
    import SimpleITK as sitk

    size_x, size_y, size_z = reader.GetSize()
    if not 0 <= index < size_y:
        raise ValueError(f"Coronal index {index} outside [0, {size_y - 1}]")
    reader.SetExtractIndex([0, index, 0])
    reader.SetExtractSize([size_x, 1, size_z])
    return np.asarray(sitk.GetArrayFromImage(reader.Execute())).squeeze().astype(np.float64)


def shifted_on_fixed(reference: np.ndarray, dx: int, dy: int) -> np.ndarray:
    """Place unchanged source voxels on the fixed grid for a pure XY origin shift."""
    before = np.zeros_like(reference)
    target_x0 = max(0, -dx)
    target_x1 = min(reference.shape[1], reference.shape[1] - dx)
    target_y0 = max(0, -dy)
    target_y1 = min(reference.shape[0], reference.shape[0] - dy)
    before[target_y0:target_y1, target_x0:target_x1] = reference[
        target_y0 + dy : target_y1 + dy,
        target_x0 + dx : target_x1 + dx,
    ]
    return before


def shifted_coronal_on_fixed(source: np.ndarray, dx: int, output_width: int) -> np.ndarray:
    """Apply the X component of the metadata shift to a coronal source plane."""
    before = np.zeros((source.shape[0], output_width), dtype=source.dtype)
    target_x0 = max(0, -dx)
    target_x1 = min(output_width, output_width - dx)
    before[:, target_x0:target_x1] = source[:, target_x0 + dx : target_x1 + dx]
    return before


def update_moments(state: dict[str, float], value: np.ndarray, target: np.ndarray, mask: np.ndarray) -> None:
    """Update streaming correlation and absolute-error moments."""
    x = value[mask]
    y = target[mask]
    state["n"] += x.size
    state["sx"] += float(x.sum())
    state["sy"] += float(y.sum())
    state["sxx"] += float((x * x).sum())
    state["syy"] += float((y * y).sum())
    state["sxy"] += float((x * y).sum())
    state["sae"] += float(np.abs(x - y).sum())


def finish_moments(state: dict[str, float]) -> tuple[float, float]:
    """Return NCC and MAE from streaming moments."""
    count = state["n"]
    covariance = state["sxy"] - state["sx"] * state["sy"] / count
    variance_x = state["sxx"] - state["sx"] ** 2 / count
    variance_y = state["syy"] - state["sy"] ** 2 / count
    return covariance / np.sqrt(variance_x * variance_y), state["sae"] / count


def histogram_percentile(histogram: np.ndarray, edges: np.ndarray, quantile: float) -> float:
    """Approximate a percentile from a bounded streaming histogram."""
    index = int(np.searchsorted(np.cumsum(histogram), quantile * histogram.sum()))
    index = min(index, len(edges) - 2)
    return float((edges[index] + edges[index + 1]) / 2)


def validate_registration(
    fixed_path: Path,
    reference_path: Path,
    moving_path: Path,
    moved_path: Path,
    dvf_path: Path,
) -> RegistrationSummary:
    """Validate all slices without holding a complete volume in memory."""
    fixed_reader = image_reader(fixed_path)
    reference_reader = image_reader(reference_path)
    moving_reader = image_reader(moving_path)
    moved_reader = image_reader(moved_path)
    dvf_reader = image_reader(dvf_path)
    require_matching_grid(reference_reader, fixed_reader, "Aligned MR")
    require_matching_grid(moving_reader, reference_reader, "Controlled-offset MR", compare_origin=False)
    require_matching_grid(moved_reader, fixed_reader, "Moved image")
    require_matching_grid(dvf_reader, fixed_reader, "DVF")
    if dvf_reader.GetNumberOfComponents() != 3:
        raise ValueError("Expected a three-component physical displacement field")
    spacing = fixed_reader.GetSpacing()
    voxel_offset = (np.asarray(fixed_reader.GetOrigin()) - np.asarray(moving_reader.GetOrigin())) / np.asarray(spacing)
    if not np.allclose(voxel_offset, np.rint(voxel_offset)):
        raise ValueError("Controlled moving-image origin offset must align with the voxel grid")
    dx, dy, dz = (int(value) for value in np.rint(voxel_offset))
    if dz != 0:
        raise ValueError("The controlled proof expects an in-plane XY origin offset only")
    template = dict.fromkeys(("n", "sx", "sy", "sxx", "syy", "sxy", "sae"), 0.0)
    before_state = template.copy()
    after_state = template.copy()
    edges = np.linspace(0, 120, 1201)
    histogram = np.zeros(len(edges) - 1, dtype=np.int64)
    magnitude_sum = 0.0
    magnitude_count = 0
    magnitude_max = 0.0
    for z_index in range(fixed_reader.GetSize()[2]):
        reference = read_axial(reference_reader, z_index)
        moving_source = read_axial(moving_reader, z_index)
        if not np.array_equal(moving_source, reference, equal_nan=True):
            raise ValueError(f"Controlled moving-image voxel values differ from the aligned MR at Z={z_index}")
        moved = read_axial(moved_reader, z_index)
        field = read_axial(dvf_reader, z_index)
        before = shifted_on_fixed(moving_source, dx, dy)
        mask = np.isfinite(reference) & (reference > 0)
        update_moments(before_state, before, reference, mask)
        update_moments(after_state, moved, reference, mask)
        magnitude = np.linalg.norm(field, axis=-1)[mask]
        histogram += np.histogram(magnitude, bins=edges)[0]
        magnitude_sum += float(magnitude.sum())
        magnitude_count += magnitude.size
        magnitude_max = max(magnitude_max, float(magnitude.max(initial=0)))
    before_ncc, before_mae = finish_moments(before_state)
    after_ncc, after_mae = finish_moments(after_state)
    return RegistrationSummary(
        before_ncc=before_ncc,
        after_ncc=after_ncc,
        before_mae=before_mae,
        after_mae=after_mae,
        dvf_mean=magnitude_sum / magnitude_count,
        dvf_p95=histogram_percentile(histogram, edges, 0.95),
        dvf_p99=histogram_percentile(histogram, edges, 0.99),
        dvf_max=magnitude_max,
        dx=dx,
        dy=dy,
    )


def contour(mask: np.ndarray) -> np.ndarray:
    """Return a two-pixel-safe inner boundary without an imaging dependency."""
    selected = np.asarray(mask, dtype=bool)
    eroded = selected.copy()
    for shift, axis in ((1, 0), (-1, 0), (1, 1), (-1, 1)):
        eroded &= np.roll(selected, shift, axis=axis)
    boundary = selected & ~eroded
    return boundary | np.roll(boundary, 1, axis=0)


def overlay_ct_contours(mr: Image.Image, ct: np.ndarray) -> Image.Image:
    """Overlay fixed-CT contours in classic grayscale on an MR plane."""
    output = np.asarray(mr.convert("RGB"), dtype=np.float32).copy()
    body_boundary = contour(ct > -800)
    bone_boundary = contour(ct > 180)
    output[body_boundary] = (190, 190, 190)
    output[bone_boundary] = (235, 235, 235)
    return Image.fromarray(np.asarray(output, dtype=np.uint8), mode="RGB")


def displacement_image(base: Image.Image, field: np.ndarray, maximum: float) -> Image.Image:
    """Render field magnitude plus sparse vectors in classic grayscale."""
    magnitude = np.linalg.norm(field, axis=-1)
    base_array = np.asarray(base.convert("L"), dtype=np.float32)
    field_gray = 18 + np.clip(magnitude / maximum, 0, 1) * 219
    output = np.repeat((base_array * 0.25 + field_gray * 0.75)[..., None], 3, axis=-1)
    image = Image.fromarray(np.asarray(np.clip(output, 0, 255), dtype=np.uint8), mode="RGB")
    draw = ImageDraw.Draw(image)
    for y in range(10, field.shape[0] - 10, 18):
        for x in range(10, field.shape[1] - 10, 18):
            delta_x = float(field[y, x, 0]) / 2.0
            delta_y = float(field[y, x, 2]) / 2.0
            end = (x + delta_x, y + delta_y)
            draw.line((x, y, *end), fill="#f0f0f0", width=1)
            draw.ellipse((end[0] - 1.5, end[1] - 1.5, end[0] + 1.5, end[1] + 1.5), fill="#f0f0f0")
    return image


def colour_bar(maximum: float, width: int, height: int = 10) -> Image.Image:
    """Create the same quantitative palette used for the displacement map."""
    gradient = np.linspace(18, 237, width, dtype=np.uint8)[None, :]
    grayscale = np.repeat(gradient[..., None], 3, axis=-1)
    return Image.fromarray(grayscale, mode="RGB").resize((width, height))


def card(
    image: Image.Image,
    title: str,
    subtitle: str,
    footer: str,
    bar: tuple[float, str] | None = None,
) -> Image.Image:
    """Compose one registration evidence card."""
    canvas = Image.new("RGB", (CARD_WIDTH, CARD_HEIGHT), BACKGROUND)
    draw = ImageDraw.Draw(canvas)
    _, heading_font, body_font, mono_font = fonts()
    draw.rounded_rectangle((3, 3, CARD_WIDTH - 4, CARD_HEIGHT - 4), radius=20, fill=CARD)
    draw.rounded_rectangle((24, 20, 84, 26), radius=3, fill=ACCENT)
    draw.text((24, 37), title, fill=INK, font=heading_font)
    draw.text((24, 66), subtitle, fill=MUTED, font=body_font)
    canvas.paste(fit(image), (24, 94))
    draw.rounded_rectangle((23, 93, 446, 445), radius=5, outline="#b8cac7", width=1)
    if bar is None:
        draw.rounded_rectangle((24, 456, 446, 484), radius=12, fill="#deebe9")
        draw.text((36, 462), footer.upper(), fill=INK, font=mono_font)
    else:
        canvas.paste(colour_bar(bar[0], 410), (30, 450))
        draw.text((30, 463), "0", fill=MUTED, font=mono_font)
        maximum_label = f"{bar[0]:.1f} {bar[1]}"
        width = draw.textbbox((0, 0), maximum_label, font=mono_font)[2]
        draw.text((440 - width, 463), maximum_label, fill=MUTED, font=mono_font)
    return canvas


def compose(cards: list[Image.Image], columns: int, output: Path, summary: RegistrationSummary) -> None:
    """Compose a desktop or mobile registration board."""
    side = 30 if columns > 1 else 15
    gap = 20
    header_height = 170 if columns > 1 else 230
    rows = int(np.ceil(len(cards) / columns))
    width = side * 2 + columns * CARD_WIDTH + (columns - 1) * gap
    height = header_height + rows * CARD_HEIGHT + (rows - 1) * gap + 94
    canvas = Image.new("RGB", (width, height), BACKGROUND)
    draw = ImageDraw.Draw(canvas)
    title_font, _, body_font, mono_font = fonts()
    if columns > 1:
        draw.text((side + 12, 28), "Registration you can inspect.", fill=INK, font=title_font)
        draw.text(
            (side + 14, 76),
            "Known geometry offset → ConvexAdam_Composite → moved MR + physical displacement field",
            fill=MUTED,
            font=body_font,
        )
        badges = (
            "REAL MR/CT",
            "CONTROLLED +20 / -12 MM",
            f"NCC {summary.before_ncc:.3f} → {summary.after_ncc:.3f}",
        )
        badge_x = side + 14
        for label in badges:
            label_width = draw.textbbox((0, 0), label, font=mono_font)[2] + 30
            draw.rounded_rectangle((badge_x, 112, badge_x + label_width, 146), radius=15, fill="#d6e8e5")
            draw.text((badge_x + 15, 120), label, fill=INK, font=mono_font)
            badge_x += label_width + 12
    else:
        draw.multiline_text(
            (side + 12, 22),
            "Real registration.\nInspectable field.",
            fill=INK,
            font=title_font,
            spacing=2,
        )
        draw.multiline_text(
            (side + 13, 106),
            "Known offset → moved MR →\nphysical displacement field",
            fill=MUTED,
            font=body_font,
            spacing=4,
        )
        draw.rounded_rectangle((side + 13, 169, width - side - 13, 207), radius=16, fill="#d6e8e5")
        draw.text((side + 28, 179), "REAL DATA · CONTROLLED OFFSET · FIXED GRID", fill=INK, font=mono_font)
    for index, item in enumerate(cards):
        x = side + (index % columns) * (CARD_WIDTH + gap)
        y = header_height + (index // columns) * (CARD_HEIGHT + gap)
        canvas.paste(item, (x, y))
    footer_y = height - 66
    draw.rounded_rectangle((side, footer_y, width - side, height - 18), radius=18, fill=INK)
    footer = (
        f"NCC {summary.before_ncc:.3f} → {summary.after_ncc:.3f} · OUTPUTS ON THE FIXED GRID"
        if columns > 1
        else f"NCC {summary.before_ncc:.3f} → {summary.after_ncc:.3f} · FIXED GRID"
    )
    footer_width = draw.textbbox((0, 0), footer, font=mono_font)[2]
    draw.text(((width - footer_width) // 2, footer_y + 16), footer, fill="#c8e0dc", font=mono_font)
    output.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(output, optimize=True)
    print(f"Wrote {output}")


def save_images(images: list[Image.Image], output_dir: Path) -> None:
    """Write image-only registration stages; captions belong to the HTML page."""
    output_dir.mkdir(parents=True, exist_ok=True)
    slugs = ("moving-before", "fixed-ct", "moved-after", "displacement-field")
    for slug, image in zip(slugs, images, strict=True):
        fit(image).save(output_dir / f"{slug}.png", optimize=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fixed", type=Path, required=True)
    parser.add_argument("--aligned-reference", type=Path, required=True)
    parser.add_argument("--moving", type=Path, required=True)
    parser.add_argument("--moved", type=Path, required=True)
    parser.add_argument("--dvf", type=Path, required=True)
    parser.add_argument("--coronal-index", type=int, default=125)
    parser.add_argument("--output", type=Path, help="Optional desktop composite proof-board output.")
    parser.add_argument("--mobile-output", type=Path, help="Optional mobile composite proof-board output.")
    parser.add_argument("--cards-dir", type=Path, default=CARDS_DIR)
    args = parser.parse_args()

    summary = validate_registration(args.fixed, args.aligned_reference, args.moving, args.moved, args.dvf)
    fixed_reader = image_reader(args.fixed)
    moving_reader = image_reader(args.moving)
    moved_reader = image_reader(args.moved)
    dvf_reader = image_reader(args.dvf)
    source_index = args.coronal_index + summary.dy
    if not np.isclose(
        plane_coordinate(fixed_reader, 1, args.coronal_index),
        plane_coordinate(moving_reader, 1, source_index),
    ):
        raise ValueError("Moving and fixed coronal planes do not occupy the same physical position")
    fixed = read_coronal(fixed_reader, args.coronal_index)
    moving_source = read_coronal(moving_reader, source_index)
    moving = shifted_coronal_on_fixed(moving_source, summary.dx, fixed.shape[1])
    moved = read_coronal(moved_reader, args.coronal_index)
    field = read_coronal(dvf_reader, args.coronal_index)
    crop = body_crop(fixed, margin=8)
    fixed_crop = crop_array(fixed, crop)
    moving_crop = crop_array(moving, crop)
    moved_crop = crop_array(moved, crop)
    field_crop = crop_array(field, crop)
    fixed_image = ImageOps.flip(window_gray(fixed_crop, -250, 450))
    moving_image = ImageOps.flip(overlay_ct_contours(robust_gray(moving_crop), fixed_crop))
    moved_image = ImageOps.flip(overlay_ct_contours(robust_gray(moved_crop), fixed_crop))
    field_maximum = summary.dvf_p99
    field_image = ImageOps.flip(displacement_image(window_gray(fixed_crop, -250, 450), field_crop, field_maximum))
    coronal_position = fixed_reader.GetOrigin()[1] + args.coronal_index * fixed_reader.GetSpacing()[1]
    save_images([moving_image, fixed_image, moved_image, field_image], args.cards_dir)
    cards = [
        card(
            moving_image,
            "1. Moving MR — before",
            "Fixed-CT contours expose the known offset",
            f"NCC TO ALIGNED MR {summary.before_ncc:.3f}",
        ),
        card(
            fixed_image,
            "2. Fixed CT target",
            f"Reference geometry · coronal y={coronal_position:+.0f} mm",
            "222 x 226 x 124 · 2 MM GRID",
        ),
        card(
            moved_image,
            "3. Moved MR — after",
            "ConvexAdam_Composite output on fixed grid",
            f"NCC {summary.after_ncc:.3f} · MAE {summary.after_mae:.2f}",
        ),
        card(
            field_image,
            "4. Displacement field",
            f"Mean {summary.dvf_mean:.2f} mm · p95 {summary.dvf_p95:.2f} mm",
            "",
            bar=(field_maximum, "mm"),
        ),
    ]
    if args.output is not None:
        compose(cards, columns=2, output=args.output, summary=summary)
    if args.mobile_output is not None:
        compose(cards, columns=1, output=args.mobile_output, summary=summary)


if __name__ == "__main__":
    main()
