# Copyright (c) 2025 Valentin Boussot
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""Build image-only ImpactSynth/TotalSegmentator evidence panels.

The SimpleITK extraction API returns one requested plane from each volume.
Compressed sources may still be decompressed internally by the imaging backend.
Composite desktop/mobile proof boards remain available through explicit output
arguments, but are not generated by default.
"""

from __future__ import annotations

import argparse
import colorsys
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont, ImageOps

PANELS_OUTPUT_DIR = Path(__file__).parents[1] / "source" / "_static" / "apps" / "impact-synth"
BACKGROUND = "#e8f0ef"
CARD = "#f8fbfa"
INK = "#123f3e"
MUTED = "#607775"
ACCENT = "#1a9a91"
CARD_WIDTH = 470
CARD_HEIGHT = 500
IMAGE_SIZE = (422, 350)


@dataclass(frozen=True)
class Plane:
    """One extracted axial plane and its complete source geometry."""

    data: np.ndarray
    size: tuple[int, int, int]
    spacing: tuple[float, float, float]
    origin: tuple[float, float, float]
    direction: tuple[float, ...]
    axial_position: float
    z_position: float


def fonts() -> tuple[ImageFont.FreeTypeFont | ImageFont.ImageFont, ...]:
    """Load a portable documentation font stack."""
    try:
        return (
            ImageFont.truetype("DejaVuSans-Bold.ttf", 34),
            ImageFont.truetype("DejaVuSans-Bold.ttf", 21),
            ImageFont.truetype("DejaVuSans.ttf", 15),
            ImageFont.truetype("DejaVuSansMono.ttf", 13),
        )
    except OSError:
        fallback = ImageFont.load_default()
        return fallback, fallback, fallback, fallback


def read_axial_plane(path: Path, index: int) -> Plane:
    """Request one Z plane through SimpleITK's extraction API."""
    import SimpleITK as sitk

    reader = sitk.ImageFileReader()
    reader.SetFileName(str(path))
    reader.ReadImageInformation()
    size = reader.GetSize()
    if len(size) != 3:
        raise ValueError(f"Expected a 3-D scalar image at {path}, got size {size}")
    if not 0 <= index < size[2]:
        raise ValueError(f"Z index {index} is outside [0, {size[2] - 1}] for {path}")
    if reader.GetNumberOfComponents() != 1:
        raise ValueError(f"Expected a scalar image at {path}")
    reader.SetExtractIndex([0, 0, index])
    reader.SetExtractSize([size[0], size[1], 1])
    image = reader.Execute()
    array = np.asarray(sitk.GetArrayFromImage(image)).squeeze().astype(np.float32)
    spacing = np.asarray(reader.GetSpacing(), dtype=np.float64)
    origin = np.asarray(reader.GetOrigin(), dtype=np.float64)
    direction = np.asarray(reader.GetDirection(), dtype=np.float64).reshape(3, 3)
    plane_origin = origin + direction @ np.asarray((0.0, 0.0, index * spacing[2]))
    return Plane(
        data=array,
        size=tuple(int(value) for value in size),
        spacing=tuple(float(value) for value in spacing),
        origin=tuple(float(value) for value in origin),
        direction=tuple(float(value) for value in direction.ravel()),
        axial_position=float(np.dot(direction[:, 2], plane_origin)),
        z_position=float(plane_origin[2]),
    )


def require_same_grid_plane(name: str, plane: Plane, reference: Plane) -> None:
    """Require identical 3-D geometry and the same extracted physical plane."""
    if plane.size != reference.size or plane.data.shape != reference.data.shape:
        raise ValueError(f"{name} does not share the reference image size")
    for field in ("spacing", "origin", "direction"):
        if not np.allclose(getattr(plane, field), getattr(reference, field)):
            raise ValueError(f"{name} does not share the reference image {field}")
    if not np.isclose(plane.axial_position, reference.axial_position):
        raise ValueError(f"{name} was not read at the reference physical axial position")


def body_crop(ct: np.ndarray, margin: int = 10) -> tuple[int, int, int, int]:
    """Find a shared crop from the CT foreground without loading another plane."""
    foreground = np.isfinite(ct) & (ct > -950)
    y_indices, x_indices = np.where(foreground)
    if not x_indices.size:
        return 0, ct.shape[1], 0, ct.shape[0]
    x0 = max(0, int(x_indices.min()) - margin)
    x1 = min(ct.shape[1], int(x_indices.max()) + margin + 1)
    y0 = max(0, int(y_indices.min()) - margin)
    y1 = min(ct.shape[0], int(y_indices.max()) + margin + 1)
    return x0, x1, y0, y1


def map_crop(crop: tuple[int, int, int, int], source: Plane, target: Plane) -> tuple[int, int, int, int]:
    """Map an axis-aligned XY crop between images using physical coordinates."""
    if not np.allclose(source.direction, target.direction):
        raise ValueError("All proof planes must share the same direction matrix")
    if not np.allclose(np.asarray(source.direction).reshape(3, 3), np.eye(3)):
        raise ValueError("The proof crop mapper requires axis-aligned image directions")
    x0, x1, y0, y1 = crop
    physical = (
        source.origin[0] + x0 * source.spacing[0],
        source.origin[0] + x1 * source.spacing[0],
        source.origin[1] + y0 * source.spacing[1],
        source.origin[1] + y1 * source.spacing[1],
    )
    mapped = (
        round((physical[0] - target.origin[0]) / target.spacing[0]),
        round((physical[1] - target.origin[0]) / target.spacing[0]),
        round((physical[2] - target.origin[1]) / target.spacing[1]),
        round((physical[3] - target.origin[1]) / target.spacing[1]),
    )
    return (
        max(0, mapped[0]),
        min(target.data.shape[1], mapped[1]),
        max(0, mapped[2]),
        min(target.data.shape[0], mapped[3]),
    )


def crop_array(array: np.ndarray, crop: tuple[int, int, int, int]) -> np.ndarray:
    """Apply an XY crop to an array stored in YX order."""
    x0, x1, y0, y1 = crop
    return np.asarray(array[y0:y1, x0:x1])


def window_gray(array: np.ndarray, low: float, high: float) -> Image.Image:
    """Window a scalar array into an 8-bit grayscale image."""
    scaled = np.clip((np.asarray(array, dtype=np.float32) - low) / max(high - low, 1e-6), 0, 1)
    return Image.fromarray(np.asarray(scaled * 255, dtype=np.uint8), mode="L").convert("RGB")


def robust_gray(array: np.ndarray) -> Image.Image:
    """Use a robust MR window while keeping the background black."""
    values = np.asarray(array, dtype=np.float32)
    finite = values[np.isfinite(values)]
    low, high = np.percentile(finite, (1.0, 99.5)) if finite.size else (0.0, 1.0)
    return window_gray(values, float(low), float(high))


def label_color(label: int) -> tuple[int, int, int]:
    """Return a deterministic high-contrast colour for an anatomical label."""
    hue = (label * 0.61803398875) % 1.0
    red, green, blue = colorsys.hsv_to_rgb(hue, 0.72, 0.98)
    return round(red * 255), round(green * 255), round(blue * 255)


def segmentation_overlay(base: Image.Image, labels: np.ndarray) -> Image.Image:
    """Overlay genuine label regions and emphasize their boundaries."""
    label_values = np.asarray(labels, dtype=np.int32)
    output = np.asarray(base.convert("RGB"), dtype=np.float32).copy()
    colour = np.zeros_like(output)
    for label in np.unique(label_values):
        if label > 0:
            colour[label_values == label] = label_color(int(label))
    selected = label_values > 0
    output[selected] = output[selected] * 0.62 + colour[selected] * 0.38
    boundary = selected & (
        (label_values != np.roll(label_values, 1, axis=0))
        | (label_values != np.roll(label_values, -1, axis=0))
        | (label_values != np.roll(label_values, 1, axis=1))
        | (label_values != np.roll(label_values, -1, axis=1))
    )
    output[boundary] = colour[boundary]
    return Image.fromarray(np.asarray(np.clip(output, 0, 255), dtype=np.uint8), mode="RGB")


HEAT_STOPS = np.asarray(
    [
        (8, 29, 88),
        (37, 106, 171),
        (65, 182, 196),
        (254, 217, 118),
        (227, 26, 28),
    ],
    dtype=np.float32,
)


def heat_colours(values: np.ndarray, maximum: float) -> np.ndarray:
    """Map values to a perceptually ordered blue-to-red palette."""
    scaled = np.clip(np.asarray(values, dtype=np.float32) / max(maximum, 1e-6), 0, 1)
    position = scaled * (len(HEAT_STOPS) - 1)
    lower = np.floor(position).astype(np.int32)
    upper = np.minimum(lower + 1, len(HEAT_STOPS) - 1)
    fraction = (position - lower)[..., None]
    return HEAT_STOPS[lower] * (1 - fraction) + HEAT_STOPS[upper] * fraction


def heat_overlay(base: Image.Image, values: np.ndarray, maximum: float, mask: np.ndarray) -> Image.Image:
    """Overlay a quantitative map while retaining anatomical context."""
    output = np.asarray(base.convert("RGB"), dtype=np.float32).copy()
    colour = heat_colours(values, maximum)
    selected = np.asarray(mask, dtype=bool) & np.isfinite(values)
    output[selected] = output[selected] * 0.32 + colour[selected] * 0.68
    return Image.fromarray(np.asarray(np.clip(output, 0, 255), dtype=np.uint8), mode="RGB")


def fit(image: Image.Image) -> Image.Image:
    """Fit a medical plane into the fixed card viewport."""
    contained = ImageOps.contain(image.convert("RGB"), IMAGE_SIZE, method=Image.Resampling.LANCZOS)
    result = Image.new("RGB", IMAGE_SIZE, "#071110")
    result.paste(contained, ((IMAGE_SIZE[0] - contained.width) // 2, (IMAGE_SIZE[1] - contained.height) // 2))
    return result


def save_panels(images: list[tuple[str, Image.Image]], output_dir: Path) -> None:
    """Write image-only App stages; titles, metrics, and legends stay in HTML."""
    output_dir.mkdir(parents=True, exist_ok=True)
    for slug, image in images:
        output = output_dir / f"{slug}.png"
        fit(image).save(output, optimize=True)
        print(f"Wrote {output}")


def metric(path: Path, key: str) -> float:
    """Read one real per-case metric from a completed KonfAI JSON artifact."""
    payload = json.loads(path.read_text(encoding="utf-8"))
    values = payload["case"][key]
    return float(next(iter(values.values())))


def draw_colour_bar(
    canvas: Image.Image,
    draw: ImageDraw.ImageDraw,
    x: int,
    y: int,
    width: int,
    maximum: float,
    unit: str,
    mono_font: ImageFont.FreeTypeFont | ImageFont.ImageFont,
) -> None:
    """Draw a compact quantitative legend inside a card."""
    gradient = np.linspace(0, maximum, width, dtype=np.float32)[None, :]
    bar = Image.fromarray(np.asarray(heat_colours(gradient, maximum), dtype=np.uint8), mode="RGB")
    canvas.paste(bar.resize((width, 10)), (x, y))
    draw.text((x, y + 13), "0", font=mono_font, fill=MUTED)
    label = f"{maximum:.0f} {unit}"
    label_width = draw.textbbox((0, 0), label, font=mono_font)[2]
    draw.text((x + width - label_width, y + 13), label, font=mono_font, fill=MUTED)


def card(
    image: Image.Image,
    title: str,
    subtitle: str,
    footer: str,
    colour_bar: tuple[float, str] | None = None,
) -> Image.Image:
    """Compose one evidence card."""
    canvas = Image.new("RGB", (CARD_WIDTH, CARD_HEIGHT), BACKGROUND)
    draw = ImageDraw.Draw(canvas)
    _, heading_font, body_font, mono_font = fonts()
    draw.rounded_rectangle((3, 3, CARD_WIDTH - 4, CARD_HEIGHT - 4), radius=20, fill=CARD)
    draw.rounded_rectangle((24, 20, 84, 26), radius=3, fill=ACCENT)
    draw.text((24, 37), title, fill=INK, font=heading_font)
    draw.text((24, 66), subtitle, fill=MUTED, font=body_font)
    viewport = fit(image)
    canvas.paste(viewport, (24, 94))
    draw.rounded_rectangle((23, 93, 446, 445), radius=5, outline="#b8cac7", width=1)
    if colour_bar is not None:
        draw_colour_bar(canvas, draw, 30, 450, 410, colour_bar[0], colour_bar[1], mono_font)
    else:
        draw.rounded_rectangle((24, 456, 446, 484), radius=12, fill="#deebe9")
        draw.text((36, 462), footer.upper(), fill=INK, font=mono_font)
    return canvas


def compose(cards: list[Image.Image], columns: int, header_height: int, output: Path, revision: str) -> None:
    """Compose a desktop or mobile proof board."""
    gap = 20
    side = 30 if columns > 1 else 15
    rows = int(np.ceil(len(cards) / columns))
    width = side * 2 + columns * CARD_WIDTH + (columns - 1) * gap
    height = header_height + rows * CARD_HEIGHT + (rows - 1) * gap + 94
    canvas = Image.new("RGB", (width, height), BACKGROUND)
    draw = ImageDraw.Draw(canvas)
    title_font, _, body_font, mono_font = fonts()
    if columns > 1:
        draw.text((side + 12, 28), "One real case. The complete App workflow.", fill=INK, font=title_font)
        draw.text(
            (side + 14, 76),
            "MR → ImpactSynth → synthetic CT → TotalSegmentator → evaluation → uncertainty",
            fill=MUTED,
            font=body_font,
        )
        badges = ("REAL ABDOMINAL MR/CT", "5 CHECKPOINTS · 3 STATES", f"KONFAI {revision}")
        badge_x = side + 14
        for label in badges:
            label_width = draw.textbbox((0, 0), label, font=mono_font)[2] + 30
            draw.rounded_rectangle((badge_x, 112, badge_x + label_width, 146), radius=15, fill="#d6e8e5")
            draw.text((badge_x + 15, 120), label, fill=INK, font=mono_font)
            badge_x += label_width + 12
    else:
        draw.multiline_text(
            (side + 12, 22),
            "Real data.\nOne App workflow.",
            fill=INK,
            font=title_font,
            spacing=2,
        )
        draw.multiline_text(
            (side + 13, 106),
            "MR → sCT → anatomy →\nevaluation → uncertainty",
            fill=MUTED,
            font=body_font,
            spacing=4,
        )
        draw.rounded_rectangle((side + 13, 169, width - side - 13, 207), radius=16, fill="#d6e8e5")
        draw.text((side + 28, 179), f"REAL DATA · 15 STATES · KONFAI {revision}", fill=INK, font=mono_font)
    for index, item in enumerate(cards):
        x = side + (index % columns) * (CARD_WIDTH + gap)
        y = header_height + (index // columns) * (CARD_HEIGHT + gap)
        canvas.paste(item, (x, y))
    footer_y = height - 66
    draw.rounded_rectangle((side, footer_y, width - side, height - 18), radius=18, fill=INK)
    footer = (
        "REAL VOLUMES · REGION-READ PLANES · OUTPUTS FROM THE PUBLISHED APPS"
        if columns > 1
        else "REAL VOLUMES · REAL APP OUTPUTS"
    )
    footer_width = draw.textbbox((0, 0), footer, font=mono_font)[2]
    draw.text(((width - footer_width) // 2, footer_y + 16), footer, fill="#c8e0dc", font=mono_font)
    output.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(output, quality=92, method=6)
    print(f"Wrote {output}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mr", type=Path, required=True)
    parser.add_argument("--sct", type=Path, required=True)
    parser.add_argument("--ct", type=Path, required=True)
    parser.add_argument("--segmentation", type=Path, required=True)
    parser.add_argument("--mae-map", type=Path, required=True)
    parser.add_argument("--uncertainty", type=Path, required=True)
    parser.add_argument("--evaluation-metrics", type=Path, required=True)
    parser.add_argument("--uncertainty-metrics", type=Path, required=True)
    parser.add_argument("--z-index", type=int, default=84)
    parser.add_argument("--uncertainty-z-index", type=int, default=56)
    parser.add_argument("--revision", default="5195b79")
    parser.add_argument("--output", type=Path, help="Optional desktop composite proof-board output.")
    parser.add_argument("--mobile-output", type=Path, help="Optional mobile composite proof-board output.")
    parser.add_argument(
        "--panels-output-dir",
        type=Path,
        default=PANELS_OUTPUT_DIR,
        help="Directory for six image-only PNG panels (default: docs/source/_static/apps/impact-synth).",
    )
    args = parser.parse_args()

    mr = read_axial_plane(args.mr, args.z_index)
    sct = read_axial_plane(args.sct, args.z_index)
    ct = read_axial_plane(args.ct, args.z_index)
    segmentation = read_axial_plane(args.segmentation, args.z_index)
    mae = read_axial_plane(args.mae_map, args.z_index)
    uncertainty = read_axial_plane(args.uncertainty, args.uncertainty_z_index)
    for name, plane in (("MR", mr), ("sCT", sct), ("segmentation", segmentation), ("MAE", mae)):
        require_same_grid_plane(name, plane, ct)
    if not np.allclose(uncertainty.direction, ct.direction):
        raise ValueError("Uncertainty does not share the CT direction matrix")
    if not np.isclose(uncertainty.axial_position, ct.axial_position):
        raise ValueError("Uncertainty was not read at the CT physical axial position")

    crop = body_crop(ct.data)
    uncertainty_crop = map_crop(crop, ct, uncertainty)
    mr_array = crop_array(mr.data, crop)
    sct_array = crop_array(sct.data, crop)
    ct_array = crop_array(ct.data, crop)
    segmentation_array = crop_array(segmentation.data, crop)
    mae_array = crop_array(mae.data, crop)
    uncertainty_array = crop_array(uncertainty.data, uncertainty_crop)

    ct_image = window_gray(ct_array, -250, 450)
    sct_image = window_gray(sct_array, -250, 450)
    mr_image = robust_gray(mr_array)
    mae_max = max(1.0, float(np.percentile(mae_array[np.isfinite(mae_array)], 99.0)))
    body = ct_array > -950
    mae_image = heat_overlay(ct_image, mae_array, mae_max, body)
    uncertainty_max = max(
        1.0,
        float(np.percentile(uncertainty_array[np.isfinite(uncertainty_array)], 99.0)),
    )
    uncertainty_base = mr_image.resize(
        (uncertainty_array.shape[1], uncertainty_array.shape[0]),
        Image.Resampling.BILINEAR,
    )
    uncertainty_mask = Image.fromarray(np.asarray(body * 255, dtype=np.uint8), mode="L").resize(
        (uncertainty_array.shape[1], uncertainty_array.shape[0]),
        Image.Resampling.NEAREST,
    )
    uncertainty_image = heat_overlay(
        uncertainty_base,
        uncertainty_array,
        uncertainty_max,
        np.asarray(uncertainty_mask) > 0,
    )
    segmentation_image = segmentation_overlay(sct_image, segmentation_array)

    save_panels(
        [
            ("mr-input", mr_image),
            ("synthetic-ct", sct_image),
            ("reference-ct", ct_image),
            ("totalsegmentator", segmentation_image),
            ("mae-map", mae_image),
            ("uncertainty-map", uncertainty_image),
        ],
        args.panels_output_dir,
    )

    mae_value = metric(args.evaluation_metrics, "Output:Reference;Mask:MAE")
    psnr_value = metric(args.evaluation_metrics, "Output:Reference;Mask:PSNR")
    ssim_value = metric(args.evaluation_metrics, "Output:Reference;Mask:SSIM")
    uncertainty_value = metric(args.uncertainty_metrics, "Uncertainty:None:Uncertainty")
    conformity_value = metric(args.uncertainty_metrics, "Comformity:None:Comformity")
    physical_z = ct.z_position

    cards = [
        card(mr_image, "1. MR input", f"Real axial plane · z={physical_z:+.0f} mm", "REGIONAL SLICE · 2 MM GRID"),
        card(sct_image, "2. ImpactSynth sCT", "Five checkpoints · original + two TTA", "15 INFERENCE STATES"),
        card(ct_image, "3. Reference CT", "Paired reference on the same geometry", "REAL CT · 2 MM GRID"),
        card(
            segmentation_image,
            "4. TotalSegmentator",
            "Five-model total anatomy on the sCT",
            "5-MODEL TOTAL ENSEMBLE",
        ),
        card(
            mae_image,
            "5. App evaluation",
            f"MAE {mae_value:.2f} HU · PSNR {psnr_value:.2f} dB · SSIM {ssim_value:.3f}",
            "",
            colour_bar=(mae_max, "HU"),
        ),
        card(
            uncertainty_image,
            "6. App uncertainty",
            f"15 states · mean {uncertainty_value:.2f}% · disagreement {conformity_value:.3f}",
            f"MEAN {uncertainty_value:.2f}% · DISAGREEMENT {conformity_value:.3f}",
            colour_bar=(uncertainty_max, "% baseline"),
        ),
    ]
    if args.output is not None:
        compose(cards, columns=3, header_height=170, output=args.output, revision=args.revision)
    if args.mobile_output is not None:
        compose(cards, columns=1, header_height=230, output=args.mobile_output, revision=args.revision)


if __name__ == "__main__":
    main()
